# fly.toml app configuration file generated for yongin-assistant on 2024-10-31T10:49:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yongin-assistant'
primary_region = 'nrt'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
